-- Run this script in Supabase SQL Editor
-- It creates a diary table used by backend /api/diary endpoints.

create table if not exists public.diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists diary_entries_user_id_created_at_idx
  on public.diary_entries (user_id, created_at desc);
