-- Supabase user data schema for NeuralNexus
-- Run this in Supabase SQL Editor after auth is configured.

-- Generic updated_at trigger function
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 1) User profile (1:1 with auth.users)
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

-- 2) Mood logs (daily mood tracker)
create table if not exists public.mood_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mood text not null check (mood in ('😊','🙂','😐','😔','😢')),
  note text,
  recorded_on date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, recorded_on)
);

drop trigger if exists trg_mood_entries_updated_at on public.mood_entries;
create trigger trg_mood_entries_updated_at
before update on public.mood_entries
for each row execute function public.set_updated_at();

-- 3) Symptom analyzer runs
create table if not exists public.symptom_checks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  input_symptoms text[] not null default '{}',
  matched_condition text,
  risk_level text check (risk_level in ('low','medium','high','emergency')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- 4) Depression analyzer runs
create table if not exists public.depression_assessments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score_percent integer not null check (score_percent between 0 and 100),
  level text not null check (level in ('low','medium','high')),
  answers jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now()
);

-- 5) Daily diary
create table if not exists public.diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_text text not null,
  created_at timestamptz not null default now()
);

-- Helpful indexes
create index if not exists mood_entries_user_id_recorded_on_idx
  on public.mood_entries (user_id, recorded_on desc);

create index if not exists symptom_checks_user_id_created_at_idx
  on public.symptom_checks (user_id, created_at desc);

create index if not exists depression_assessments_user_id_created_at_idx
  on public.depression_assessments (user_id, created_at desc);

create index if not exists diary_entries_user_id_created_at_idx
  on public.diary_entries (user_id, created_at desc);

-- Optional but recommended: enforce row-level access for client-side usage.
alter table public.user_profiles enable row level security;
alter table public.mood_entries enable row level security;
alter table public.symptom_checks enable row level security;
alter table public.depression_assessments enable row level security;
alter table public.diary_entries enable row level security;

-- user_profiles policies
drop policy if exists user_profiles_select_own on public.user_profiles;
create policy user_profiles_select_own
on public.user_profiles for select
using (auth.uid() = user_id);

drop policy if exists user_profiles_insert_own on public.user_profiles;
create policy user_profiles_insert_own
on public.user_profiles for insert
with check (auth.uid() = user_id);

drop policy if exists user_profiles_update_own on public.user_profiles;
create policy user_profiles_update_own
on public.user_profiles for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- mood_entries policies
drop policy if exists mood_entries_select_own on public.mood_entries;
create policy mood_entries_select_own
on public.mood_entries for select
using (auth.uid() = user_id);

drop policy if exists mood_entries_insert_own on public.mood_entries;
create policy mood_entries_insert_own
on public.mood_entries for insert
with check (auth.uid() = user_id);

drop policy if exists mood_entries_update_own on public.mood_entries;
create policy mood_entries_update_own
on public.mood_entries for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists mood_entries_delete_own on public.mood_entries;
create policy mood_entries_delete_own
on public.mood_entries for delete
using (auth.uid() = user_id);

-- symptom_checks policies
drop policy if exists symptom_checks_select_own on public.symptom_checks;
create policy symptom_checks_select_own
on public.symptom_checks for select
using (auth.uid() = user_id);

drop policy if exists symptom_checks_insert_own on public.symptom_checks;
create policy symptom_checks_insert_own
on public.symptom_checks for insert
with check (auth.uid() = user_id);

drop policy if exists symptom_checks_delete_own on public.symptom_checks;
create policy symptom_checks_delete_own
on public.symptom_checks for delete
using (auth.uid() = user_id);

-- depression_assessments policies
drop policy if exists depression_assessments_select_own on public.depression_assessments;
create policy depression_assessments_select_own
on public.depression_assessments for select
using (auth.uid() = user_id);

drop policy if exists depression_assessments_insert_own on public.depression_assessments;
create policy depression_assessments_insert_own
on public.depression_assessments for insert
with check (auth.uid() = user_id);

drop policy if exists depression_assessments_delete_own on public.depression_assessments;
create policy depression_assessments_delete_own
on public.depression_assessments for delete
using (auth.uid() = user_id);

-- diary_entries policies
drop policy if exists diary_entries_select_own on public.diary_entries;
create policy diary_entries_select_own
on public.diary_entries for select
using (auth.uid() = user_id);

drop policy if exists diary_entries_insert_own on public.diary_entries;
create policy diary_entries_insert_own
on public.diary_entries for insert
with check (auth.uid() = user_id);

drop policy if exists diary_entries_delete_own on public.diary_entries;
create policy diary_entries_delete_own
on public.diary_entries for delete
using (auth.uid() = user_id);
